export const ProgramShortCodesModel = {
    "Bachelor of Technology in Computer Science & Engineering": { shortCode: "BTCSE", fullName: "Bachelor of Technology in Computer Science & Engineering" },
    "Bachelor of Technology in Civil Engineering": { shortCode: "BTCE", fullName: "Bachelor of Technology in Civil Engineering" },
    "Bachelor of Computer Applications": { shortCode: "BCA", fullName: "Bachelor of Computer Applications" },
    "Bachelor of Technology in Electrical & Electronics Engineering": { shortCode: "BTEEE", fullName: "Bachelor of Technology in Electrical & Electronics Engineering" },
    "Bachelor of Technology in Electronics & Communication Engineering": { shortCode: "BTECE", fullName: "Bachelor of Technology in Electronics & Communication Engineering" },
    "Bachelor of Technology in Mechanical Engineering": { shortCode: "BTME", fullName: "Bachelor of Technology in Mechanical Engineering" },
    "Diploma in Computer Science & Engineering": { shortCode: "DCSE", fullName: "Diploma in Computer Science & Engineering" },
    "Diploma in Civil Engineering": { shortCode: "DCE", fullName: "Diploma in Civil Engineering" },
    "Diploma in Mechanical Engineering": { shortCode: "DME", fullName: "Diploma in Mechanical Engineering" },
    "Diploma in Electrical & Electronics Engineering": { shortCode: "DEEE", fullName: "Diploma in Electrical & Electronics Engineering" },
    "Diploma in Electronics & Communication Engineering": { shortCode: "DECE", fullName: "Diploma in Electronics & Communication Engineering" },
    "Master of Computer Applications": { shortCode: "MCA", fullName: "Master of Computer Applications" },
    "Auxiliary Nursing & Midwifery": { shortCode: "ANM", fullName: "Auxiliary Nursing & Midwifery" },
    "Master of Technology in Structural Engineering": { shortCode: "MTCE", fullName: "Master of Technology in Structural Engineering" },
    "Master of Arts in Economics": { shortCode: "MA-ECO", fullName: "Master of Arts in Economics" },
    "Master of Arts in English": { shortCode: "MA-ENG", fullName: "Master of Arts in English" },
    "Master of Arts (Hons.) in Sanskrit": { shortCode: "MA-SNK", fullName: "Master of Arts (Hons.) in Sanskrit" },
    "Bachelor of Business Administration": { shortCode: "BBA", fullName: "Bachelor of Business Administration" },
    "Bachelor of Business Administration in Capital Market": { shortCode: "BBA-CM", fullName: "Bachelor of Business Administration in Capital Market" },
    "Master of Business Administration": { shortCode: "MBA", fullName: "Master of Business Administration" },
    "Bachelor of Commerce(Hons.) in Accounts": { shortCode: "BCOM-AC", fullName: "Bachelor of Commerce(Hons.) in Accounts" },
    "Bachelor of Commerce(Hons.) in E-Commerce": { shortCode: "BCOM-EC", fullName: "Bachelor of Commerce(Hons.) in E-Commerce" },
    "Bachelor of Commerce(Hons.) in Taxation": { shortCode: "BCOM-TAX", fullName: "Bachelor of Commerce(Hons.) in Taxation" },
    "Master of Commerce": { shortCode: "MCOM-AC", fullName: "Master of Commerce" },
    "Bachelor of Technology in Electrical & Electronics Engineering-LATERAL": { shortCode: "BTEEE-L", fullName: "Bachelor of Technology in Electrical & Electronics Engineering-LATERAL" },
    "Bachelor of Technology in Electronics and Communication Engineering-LATERAL": { shortCode: "BTECE-L", fullName: "Bachelor of Technology in Electronics and Communication Engineering-LATERAL" },
    "Diploma in Electrical & Electronics Engineering-LATERAL": { shortCode: "DEEE-L", fullName: "Diploma in Electrical & Electronics Engineering-LATERAL" },
    "Diploma in Electronics & Communication Engineering-LATERAL": { shortCode: "DECE-L", fullName: "Diploma in Electronics & Communication Engineering-LATERAL" },
    "Bachelor of Technology in Computer Science & Engineering-LATERAL": { shortCode: "BTCSE-L", fullName: "Bachelor of Technology in Computer Science & Engineering-LATERAL" },
    "Bachelor of Technology in Civil Engineering-LATERAL": { shortCode: "BTCE-L", fullName: "Bachelor of Technology in Civil Engineering-LATERAL" },
    "Bachelor of Technology in Mechanical Engineering-LATERAL": { shortCode: "BTME-L", fullName: "Bachelor of Technology in Mechanical Engineering-LATERAL" },
    "Diploma in Computer Science & Engineering-LATERAL": { shortCode: "DCSE-L", fullName: "Diploma in Computer Science & Engineering-LATERAL" },
    "Diploma in Civil Engineering-LATERAL": { shortCode: "DCE-L", fullName: "Diploma in Civil Engineering-LATERAL" },
    "Master of Technology in Environmental Engineering": { shortCode: "MENV", fullName: "Master of Technology in Environmental Engineering" },
    "Diploma in Mechanical Engineering-LATERAL": { shortCode: "DME-L", fullName: "Diploma in Mechanical Engineering-LATERAL" },
    "Bachelor of Arts (Hons.) in Economics": { shortCode: "BA-ECO", fullName: "Bachelor of Arts (Hons.) in Economics" },
    "Bachelor of Arts (Hons.) in Sanskrit": { shortCode: "BA-SNK", fullName: "Bachelor of Arts (Hons.) in Sanskrit" },
    "Bachelor of Science (Hons.) in Mathematics": { shortCode: "BSCM-H", fullName: "Bachelor of Science (Hons.) in Mathematics" },
    "Bachelor of Science (Hons.) in Nursing": { shortCode: "BSC-NUR", fullName: "Bachelor of Science (Hons.) in Nursing" },
    "Bachelor of Technology in Artificial Intelligence": { shortCode: "BTAI", fullName: "Bachelor of Technology in Artificial Intelligence" },
    "Bachelor of Arts (Hons.) in English": { shortCode: "BA-ENG", fullName: "Bachelor of Arts (Hons.) in English" },
    "Bachelor of Yoga and Naturopathy": { shortCode: "BYN", fullName: "Bachelor of Yoga and Naturopathy" },
    "General Nursing & Midwifery": { shortCode: "GNM", fullName: "General Nursing & Midwifery" },
    "Master of Yoga & Naturopathy": { shortCode: "MYN", fullName: "Master of Yoga & Naturopathy" },
    "Doctor of Philosophy in Engineering": { shortCode: "PHD-CSE", fullName: "Doctor of Philosophy in Engineering" },
    "Doctor of Philosophy in Management": { shortCode: "PHD-CM", fullName: "Doctor of Philosophy in Management" },
    "Doctor of Philosophy in Humanities": { shortCode: "PHD-H", fullName: "Doctor of Philosophy in Humanities" },
    "Diploma in Yoga & Fitness Trainer": { shortCode: "DYFT", fullName: "Diploma in Yoga & Fitness Trainer" },
    "Master of Yoga & Naturopathy-LATERAL": { shortCode: "MYN-L", fullName: "Master of Yoga & Naturopathy-LATERAL" },
    "Master of Technology in Construction Technology & Management": { shortCode: "MTCTM", fullName: "Master of Technology in Construction Technology & Management" },
    "Master of Technology in Computer Science & Engineering": { shortCode: "MTCSE", fullName: "Master of Technology in Computer Science & Engineering" },
    "Master of Technology in Power System": { shortCode: "MTPS", fullName: "Master of Technology in Power System" },
    "Master of Technology in Power Electronics": { shortCode: "MTPE", fullName: "Master of Technology in Power Electronics" },
    "Master of Technology in Signal Processing": { shortCode: "MTSP", fullName: "Master of Technology in Signal Processing" },
    "Master of Technology in VLSI Design": { shortCode: "MTVLSI", fullName: "Master of Technology in VLSI Design" },
    "Master of Technology in Production Engineering": { shortCode: "MTPRE", fullName: "Master of Technology in Production Engineering" },
    "Master of Technology in Thermal Engineering": { shortCode: "MTTE", fullName: "Master of Technology in Thermal Engineering" },
    "B.Sc in Yogic Science": { shortCode: "BY", fullName: "B.Sc in Yogic Science" },
    "M.Sc in Yogic Science": { shortCode: "MY", fullName: "M.Sc in Yogic Science" },
    "Bachelor of Pharmacy": { shortCode: "B.Pharm", fullName: "Bachelor of Pharmacy" },
    "Diploma in French": { shortCode: "DFNCH", fullName: "Diploma in French" },
    "Diploma in Pharmacy": { shortCode: "D.Pharm", fullName: "Diploma in Pharmacy" },
    "BA LLB": { shortCode: "BA-LLB", fullName: "BA LLB" },
    "BCom LLB": { shortCode: "BCom-LLB", fullName: "BCom LLB" },
    "BBA LLB": { shortCode: "BBA-LLB", fullName: "BBA LLB" },
    "Bachelor of Performing Arts": { shortCode: "BPA", fullName: "Bachelor of Performing Arts" },
    "Bachelor of Business Administration in Stock Broking and Portfolio Management": { shortCode: "BBA-SBPM", fullName: "Bachelor of Business Administration in Stock Broking and Portfolio Management" },
    "Bachelor of Visual Arts": { shortCode: "BVA", fullName: "Bachelor of Visual Arts" },
    "Master of Visual Arts": { shortCode: "MVA", fullName: "Master of Visual Arts" },
    "Master of Performing Art": { shortCode: "MPA", fullName: "Master of Performing Art" },
    "Bachelor of Journalism & Mass Communication": { shortCode: "BA J&MC", fullName: "Bachelor of Journalism & Mass Communication" },
    "Bachelor of Pharmacy-LATERAL": { shortCode: "B.Pharm-L", fullName: "Bachelor of Pharmacy-LATERAL" },
    "Master of Arts in Journalism and Mass Communication": { shortCode: "MA J&MC", fullName: "Master of Arts in Journalism and Mass Communication" },
    "Bachelor of Laws": { shortCode: "BLL", fullName: "Bachelor of Laws" },
    "Master of Laws": { shortCode: "ML", fullName: "Master of Laws" },
    "BBA-TEST": { shortCode: "TEST", fullName: "BBA-TEST" },
    "M.Sc. in Data Science": { shortCode: "MSDS", fullName: "M.Sc. in Data Science" }
};